name: AI Code Review (Claude)
on:
  pull_request:
    branches: [main] # base branch đích
    paths:
      - "src/**"
      - "package.json"
      - "vite.config.*"
      - ".eslintrc.*"
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - run: npm i undici

      - name: Install Anthropic SDK (no-save)
        run: npm i --no-save @anthropic-ai/sdk@^0.27.3

      - name: Generate PR diff
        id: diff
        shell: bash
        run: |
          set -euo pipefail

          # Lấy BASE/HEAD SHA: ưu tiên event PR, fallback env, rồi tới GITHUB_SHA
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
          : "${BASE:=${PR_BASE_SHA:-}}"
          : "${HEAD:=${PR_HEAD_SHA:-${GITHUB_SHA}}}"

          echo "BASE=$BASE"
          echo "HEAD=$HEAD"

          # Đảm bảo có lịch sử 2 commit này
          git fetch --no-tags --depth=1 origin "$BASE" || true
          git fetch --no-tags --depth=1 origin "$HEAD" || true

          # Nếu có merge-base thì dùng triple-dot, nếu không thì fallback two-dot
          if git merge-base --is-ancestor "$BASE" "$HEAD" || git merge-base "$BASE" "$HEAD" >/dev/null 2>&1; then
            echo "Using triple-dot diff (BASE...HEAD)"
            git diff "$BASE...$HEAD" > pr.diff || true
          else
            echo "No merge base. Falling back to two-dot diff (BASE..HEAD)"
            git diff "$BASE..$HEAD" > pr.diff || true
          fi

          # Đảm bảo luôn có file
          [ -f pr.diff ] || : > pr.diff

          echo "diff_path=pr.diff" >> "$GITHUB_OUTPUT"

      - name: Run Claude review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Thử theo thứ tự: model bạn chắc chắn có quyền -> các phương án cũ
          CLAUDE_MODEL: "claude-sonnet-4-5, claude-3-7-sonnet, claude-3-5-sonnet-20241022, claude-3-haiku-20240307"
          REVIEW_LANG: vi
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: node scripts/ai-review.js

      - uses: actions/upload-artifact@v4
        with:
          name: ai-review-output
          path: |
            review.md
            issues.json

      - name: Post PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node scripts/post_comment.js

      - name: Create Issues (High/Critical)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: node scripts/create_issues.js
