name: AI Code Review (Claude)
on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "vite.config.*"
      - ".eslintrc.*"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - run: npm i undici

      - name: Install Anthropic SDK (no-save)
        run: npm i --no-save @anthropic-ai/sdk@^0.27.3

      - name: Generate PR diff
        id: diff
        shell: bash
        run: |
          set -euo pipefail

          # Lấy BASE/HEAD SHA
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
          : "${BASE:=${PR_BASE_SHA:-}}"
          : "${HEAD:=${PR_HEAD_SHA:-${GITHUB_SHA}}}"

          echo "BASE=$BASE"
          echo "HEAD=$HEAD"

          # Fetch đủ lịch sử để tính merge-base (depth=50 an toàn hơn)
          git fetch --no-tags --depth=50 origin "$BASE" || echo "Warn: fetch BASE failed"
          git fetch --no-tags --depth=50 origin "$HEAD" || echo "Warn: fetch HEAD failed"

          # Thử triple-dot trước; nếu không có merge-base thì fallback two-dot
          if git merge-base "$BASE" "$HEAD" >/dev/null 2>&1; then
            echo "Using triple-dot diff (BASE...HEAD)"
            git diff "$BASE...$HEAD" > pr.diff
          else
            echo "No merge base. Falling back to two-dot diff (BASE..HEAD)"
            git diff "$BASE..$HEAD" > pr.diff
          fi

          # Kiểm tra file diff có tồn tại và không rỗng
          if [ ! -s pr.diff ]; then
            echo "Warning: pr.diff is empty or missing"
            echo "# No changes detected" > pr.diff
          fi

          echo "diff_path=pr.diff" >> "$GITHUB_OUTPUT"

      - name: Run Claude review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Danh sách model fallback (script sẽ thử lần lượt nếu model trước fail)
          CLAUDE_MODEL: "claude-sonnet-4-20250514,claude-3-7-sonnet-20250219,claude-3-5-sonnet-20241022,claude-3-haiku-20240307"
          REVIEW_LANG: vi
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: node scripts/ai-review.js

      - uses: actions/upload-artifact@v4
        with:
          name: ai-review-output
          path: |
            review.md
            issues.json

      - name: Post PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node scripts/post_comment.js

      - name: Create Issues (High/Critical)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: node scripts/create_issues.js
